name: PR Checks

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  pr-checks:
    # Resuable workflow
    uses: ravalinamburi/common_scripts/.github/workflows/checks.yml@run_in_container
    with:
      run_pr_title_check: true
      run_pr_email_check: true
      run_signed_off_check: false
